eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 6

security:
  basic:
    enabled: false
